namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_INFURA_BSC_PROVIDER: string;
    NEXT_PUBLIC_INFURA_BSC_TESTNET_PROVIDER: string;
    NEXT_PUBLIC_INFURA_ETHEREUM_PROVIDER: string;
    NEXT_PUBLIC_INFURA_ETHEREUM_TESTNET_PROVIDER: string;

    NEXT_PUBLIC_UI_URL: string;

    NEXT_PUBLIC_WEB3_MODAL_PROJECT_ID: string;

    NEXT_PUBLIC_BACKEND_URL: string;
  }
}
